### PR TITLE
add unit tests for runtime/core - helpers

### PR DESCRIPTION
**Pull request by esell**
** NOTE ** there are currently a few tests that are not passing (commented in code). need to dig a bit deeper and see what is going on...

This PR adds unit tests for runtime/core per issue #34.

### CODE REVIEW

**Comment by esell** [comment]
@ziflex, would be interested to get your opinion on the strategy used in these tests as well as your thoughts on why some are failing (returning `nil`).

**Comment by ziflex** [comment]
@esell I guess those cases are not covered in the utility function.

**Comment by ziflex** [comment]
@esell here is an updated version of helper:

```go
func IsNil(input interface{}) bool {
	val := reflect.ValueOf(input)
	kind := val.Kind()

	switch kind {
	case reflect.Ptr,
		reflect.Array,
		reflect.Slice,
		reflect.Map,
		reflect.Func,
		reflect.Interface,
		reflect.Chan:
		return val.IsNil()
	case reflect.Struct,
		reflect.UnsafePointer:
		return false
	case reflect.Invalid:
		return true
	default:
		return false
	}
}
```

If I missed something else - just add.

**Comment by esell** [comment]
I took a look at https://golang.org/pkg/reflect/#Value.IsNil and it appears you got everything so i've updated the PR with those changes.

**Pull request merged**
