### PR TITLE
Add to_binary function

### PR DESCRIPTION
**Pull request by junebugfix**
This PR adds the missing `TO_BINARY` ferret function.

Let me know if there should be any changes to docs or other edits I missed :)

### CODE REVIEW

**Comment by ziflex** [comment]
Hey, thanks for the PR!
Everything looks good; just a tiny change is needed.

**Comment by ziflex** [comment]
Could you fix the linting issues, please?

**Comment by ziflex** [comment]
Eh, formatting. Could you run ``make fmt``, please?

**Comment by junebugfix** [comment]
Sorry for the back and forth! I'm not sure why the build check failed with `Binary checksum didn't match` but the formatting issues should now be fixed

**Pull request merged**
